#
# This docker-compose file is used to run the FHIR server and its dependencies in a local development environment.
# Host (or external) ports are mapped to container ports for easy access. 
#
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      # Mount the individual file or the entire directory
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm-export.json

  raven_fhir_fhirbase:
    image: gtri/mdi-fhirbase:latest
    container_name: raven_fhir_fhirbase
    ports:
      - "9432:5432"
      - "9300:3000"
    environment:
      POSTGRES_DB: cmsr4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mynewpassword
    networks:
      - raven-network
    volumes:
      - raven_fhir_fhirbase_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bluejay_fhir_fhirbase:
    image: gtri/mdi-fhirbase:latest
    container_name: bluejay_fhir_fhirbase
    ports:
      - "9433:5432"
      - "9301:3000"
    environment:
      POSTGRES_DB: cmsr4
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mynewpassword
    networks:
      - raven-network
    volumes:
      - bluejay_fhir_fhirbase_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  raven-fhir-server:
    image: gtri/mdi-fhir-server:latest
    container_name: raven-fhir-server
    ports:
      - "9080:9080"
    environment:
      - JDBC_URL=jdbc:postgresql://raven_fhir_fhirbase:5432/cmsr4
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=mynewpassword
      - JDBC_POOLSIZE=5
      - TOMCAT_PORT=9080
      - SMART_INTROSPECTURL=
      - SMART_AUTHSERVERURL=
      - SMART_TOKENSERVERURL=
      - AUTH_BASIC=client:secret
      - FHIR_READONLY=False
      - SERVER_PATH=raven-fhir-server
      - SERVERBASE_URL=http://localhost:9080/raven-fhir-server/fhir
      - INTERNAL_FHIR_REQUEST_URL=http://localhost:9080/raven-fhir-server/fhir
      - SERVER_VERSION=v2026-03-27.3.0.0-draft
      - SERVER_TYPE=cms
      - AUTH_AUDIENCE=raven-fhir-server-test-client
      - AUTH_ISSUER_URL=http://host.docker.internal:8080/realms/Raven-MDI
    networks:
      - raven-network
    depends_on:
      raven_fhir_fhirbase:
        condition: service_healthy

  bluejay-fhir-server:
    image: gtri/mdi-fhir-server:latest
    container_name: bluejay-fhir-server
    ports:
      - "9090:9090"
    environment:
      - JDBC_URL=jdbc:postgresql://bluejay_fhir_fhirbase:5432/cmsr4
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=mynewpassword
      - JDBC_POOLSIZE=5
      - TOMCAT_PORT=9090
      - SMART_INTROSPECTURL=
      - SMART_AUTHSERVERURL=
      - SMART_TOKENSERVERURL=
      - AUTH_BASIC=client:secret
      - FHIR_READONLY=False
      - SERVER_PATH=bluejay-fhir-server
      - SERVERBASE_URL=http://localhost:9090/bluejay-fhir-server/fhir
      - INTERNAL_FHIR_REQUEST_URL=http://localhost:9090/bluejay-fhir-server/fhir
      - SERVER_VERSION=v2026-03-27.3.0.0-draft
      - SERVER_TYPE=edrs
      - AUTH_AUDIENCE=bluejay-fhir-server-test-client
      - AUTH_ISSUER_URL=http://host.docker.internal:8080/realms/Raven-MDI
    networks:
      - raven-network
    depends_on:
      bluejay_fhir_fhirbase:
        condition: service_healthy

  raven-import-api:
    image: gtri/mdi-import-submit-api:latest
    container_name: raven-import-api
    ports:
      - "9999:8080"
    environment:
      - FHIRCMS_URL=http://raven-fhir-server:9080/raven-fhir-server/fhir
      - FHIRCMS_BASIC_USERNAME=client
      - FHIRCMS_BASIC_PASSWORD=secret
      - SUBMISSION_BASIC_PASSWORD=secret
      - SUBMISSION_BASIC_USERNAME=client
      - SUBMISSION_URL=http://raven-fhir-server:9080/raven-fhir-server/fhir
      - MY_URL=http://localhost:9999/raven-import-and-submit-api
    networks:
      - raven-network

networks:
  raven-network:
    driver: bridge

volumes:
  raven_fhir_fhirbase_data:
  bluejay_fhir_fhirbase_data:
